// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCopyrightAttribute("Copyright ©2013-2022 ICT Baden GmbH")]
[assembly: AssemblyCompanyAttribute("ICT Baden GmbH")]
[assembly: AssemblyProductAttribute("X-Platform and Web Application Framework")]
[assembly: AssemblyVersionAttribute("4.0.0")]
[assembly: AssemblyFileVersionAttribute("4.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyCopyright = "Copyright ©2013-2022 ICT Baden GmbH";
        internal const System.String AssemblyCompany = "ICT Baden GmbH";
        internal const System.String AssemblyProduct = "X-Platform and Web Application Framework";
        internal const System.String AssemblyVersion = "4.0.0";
        internal const System.String AssemblyFileVersion = "4.0.0";
    }
}
